=== SirDoggyJvla/pz-scripts-data/$schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Blocks Folder General Schema",
  "type": "object",
  "properties": {
    "version": { "type": ["number", "string"] },
    "name": { "type": "string" },
    "description": { "type": "string" },
    "shouldHaveParent": { "type": "boolean" },
    "parents": {
      "type": "array",
      "items": { "type": "string" }
    },
    "needsChildren": {
      "type": "array",
      "items": { "type": "string" }
    },
    "parameters": { "type": "array" }
  },
  "additionalProperties": true
}

=== SirDoggyJvla/pz-scripts-data/data/blocks/evolvedrecipe.json
{
    "version": 1.0,
    "name": "evolvedrecipe",
    "description": "Defines a dynamic recipe.",
    "parameters": [
        {
            "name": "BaseItem"
        },
        {
            "name": "MaxItems"
        },
        {
            "name": "ResultItem"
        },
        {
            "name": "Cookable"
        },
        {
            "name": "Name"
        },
        {
            "name": "Template"
        },
        {
            "name": "MinimumWater"
        },
        {
            "name": "CanAddSpicesEmpty"
        },
        {
            "name": "AddIngredientIfCooked"
        },
        {
            "name": "AddIngredientSound"
        }
    ]
}

=== SirDoggyJvla/pz-scripts-data/data/blocks/sound.json
{
    "version": 1.0,
    "name": "sound",
    "description": "Defines a sound properties.",
    "shouldHaveParent": true,
    "parents": [
        "module"
    ],
    "parameters": [
        {
            "name": "category"
        },
        {
            "name": "clip"
        },
        {
            "name": "master"
        },
        {
            "name": "loop"
        },
        {
            "name": "maxInstancesPerEmitter"
        }
    ]
}

=== SirDoggyJvla/pz-scripts-data/data/blocks/mannequin.json
{
    "version": 1.0,
    "name": "mannequin",
    "description": "Defines a mannequin tile properties.",
    "parameters": [
        {
            "name": "female"
        },
        {
            "name": "model"
        },
        {
            "name": "texture"
        },
        {
            "name": "animSet"
        },
        {
            "name": "animState"
        },
        {
            "name": "pose"
        },
        {
            "name": "outfit"
        }
    ]
}

=== SirDoggyJvla/pz-scripts-data/data/blocks/CopyFrames.json
{
    "version": 1.0,
    "$schema": "../../$schema.json",
    "name": "CopyFrames",
    "description": "It is unknown what this block does.",
    "shouldHaveParent": true,
    "parents": [
        "animation"
    ],
    "parameters": [
        {
            "name": "frame"
        },
        {
            "name": "source"
        },
        {
            "name": "sourceFrame1"
        },
        {
            "name": "sourceFrame2"
        }
    ]
}

=== SirDoggyJvla/pz-scripts-data/data/blocks/component WallCoveringConfig.json
{
    "version": 1.0,
    "$schema": "../../$schema.json",
    "name": "component WallCoveringConfig",
    "description": "",
    "shouldHaveParent": true,
    "parents": [
        "entity"
    ],
    "parameters": [
        {
            "name": "sign"
        },
        {
            "name": "type"
        }
    ]
}

=== SirDoggyJvla/pz-scripts-data/data/blocks/lightbar.json
{
    "version": 1.0,
    "$schema": "../../$schema.json",
    "name": "lightbar",
    "description": "",
    "shouldHaveParent": true,
    "parents": [
        "template",
        "vehicle"
    ],
    "parameters": [
        {
            "name": "texture"
        },
        {
            "name": "soundSiren"
        },
        {
            "name": "leftCol"
        },
        {
            "name": "rightCol"
        }
    ]
}

=== SirDoggyJvla/pz-scripts-data/data/blocks/contextEntry.json
{
    "version": 1.0,
    "$schema": "../../$schema.json",
    "name": "contextEntry",
    "description": "",
    "shouldHaveParent": true,
    "parents": [
        "component ContextMenuConfig"
    ],
    "parameters": [
        {
            "name": "menu"
        },
        {
            "name": "customFunction"
        }
    ]
}
